--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

-- Started on 2022-04-04 18:00:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3344 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 34484)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    cod_employee integer NOT NULL,
    address character varying(150),
    birthday date,
    email character varying(50) NOT NULL,
    identification character varying(255) NOT NULL,
    names character varying(50) NOT NULL,
    phone character varying(10),
    surnames character varying(50) NOT NULL,
    vaccination_status boolean
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 34483)
-- Name: employee_cod_employee_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN cod_employee ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_cod_employee_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 34492)
-- Name: employee_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_user (
    cod_user integer NOT NULL,
    password character varying(20) NOT NULL,
    role character varying(3) NOT NULL,
    username character varying(20) NOT NULL,
    employee integer NOT NULL
);


ALTER TABLE public.employee_user OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 34491)
-- Name: employee_user_cod_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_user ALTER COLUMN cod_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_user_cod_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 34498)
-- Name: vaccination_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vaccination_detail (
    cod_detail integer NOT NULL,
    vaccination_date date NOT NULL,
    vaccination_dose integer NOT NULL,
    cod_employee integer NOT NULL,
    cod_vaccine integer NOT NULL
);


ALTER TABLE public.vaccination_detail OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 34497)
-- Name: vaccination_detail_cod_detail_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vaccination_detail ALTER COLUMN cod_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vaccination_detail_cod_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 34504)
-- Name: vaccine_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vaccine_type (
    cod_vaccine integer NOT NULL,
    name character varying(15) NOT NULL
);


ALTER TABLE public.vaccine_type OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 34503)
-- Name: vaccine_type_cod_vaccine_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vaccine_type ALTER COLUMN cod_vaccine ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vaccine_type_cod_vaccine_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3332 (class 0 OID 34484)
-- Dependencies: 210
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.employee VALUES (1, NULL, NULL, 'bran-25@hotmail.com', '1719870808', 'BRANDON AARON', NULL, 'ROMERO CRUZ', false);
INSERT INTO public.employee VALUES (2, 'Quito', '1998-03-08', 'pedro@gmail.com', '1710449701', 'JOSE PEDRO', '0960122384', 'PEREZ ROSALES', true);


--
-- TOC entry 3334 (class 0 OID 34492)
-- Dependencies: 212
-- Data for Name: employee_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.employee_user VALUES (1, 'brarom123', 'EMP', 'brarom', 1);
INSERT INTO public.employee_user VALUES (2, 'josper123', 'EMP', 'josper', 2);


--
-- TOC entry 3336 (class 0 OID 34498)
-- Dependencies: 214
-- Data for Name: vaccination_detail; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.vaccination_detail VALUES (1, '2022-03-09', 1, 2, 1);


--
-- TOC entry 3338 (class 0 OID 34504)
-- Dependencies: 216
-- Data for Name: vaccine_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.vaccine_type VALUES (1, 'Sputnik');
INSERT INTO public.vaccine_type VALUES (2, 'AstraZeneca');
INSERT INTO public.vaccine_type VALUES (3, 'Pfizer');
INSERT INTO public.vaccine_type VALUES (4, 'Jhonson&Jhonson');


--
-- TOC entry 3345 (class 0 OID 0)
-- Dependencies: 209
-- Name: employee_cod_employee_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_cod_employee_seq', 2, true);


--
-- TOC entry 3346 (class 0 OID 0)
-- Dependencies: 211
-- Name: employee_user_cod_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_user_cod_user_seq', 2, true);


--
-- TOC entry 3347 (class 0 OID 0)
-- Dependencies: 213
-- Name: vaccination_detail_cod_detail_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vaccination_detail_cod_detail_seq', 1, true);


--
-- TOC entry 3348 (class 0 OID 0)
-- Dependencies: 215
-- Name: vaccine_type_cod_vaccine_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vaccine_type_cod_vaccine_seq', 1, false);


--
-- TOC entry 3180 (class 2606 OID 34490)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (cod_employee);


--
-- TOC entry 3184 (class 2606 OID 34496)
-- Name: employee_user employee_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_user
    ADD CONSTRAINT employee_user_pkey PRIMARY KEY (cod_user);


--
-- TOC entry 3182 (class 2606 OID 34510)
-- Name: employee ukbkyf1a53nbpkti0lyjvurcm5k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT ukbkyf1a53nbpkti0lyjvurcm5k UNIQUE (identification, email);


--
-- TOC entry 3186 (class 2606 OID 34502)
-- Name: vaccination_detail vaccination_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccination_detail
    ADD CONSTRAINT vaccination_detail_pkey PRIMARY KEY (cod_detail);


--
-- TOC entry 3188 (class 2606 OID 34508)
-- Name: vaccine_type vaccine_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccine_type
    ADD CONSTRAINT vaccine_type_pkey PRIMARY KEY (cod_vaccine);


--
-- TOC entry 3191 (class 2606 OID 34521)
-- Name: vaccination_detail fk10wcld59t9jphmd6n418wjae4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccination_detail
    ADD CONSTRAINT fk10wcld59t9jphmd6n418wjae4 FOREIGN KEY (cod_vaccine) REFERENCES public.vaccine_type(cod_vaccine);


--
-- TOC entry 3190 (class 2606 OID 34516)
-- Name: vaccination_detail fkkbt1wqub8lajehkqswar97f77; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vaccination_detail
    ADD CONSTRAINT fkkbt1wqub8lajehkqswar97f77 FOREIGN KEY (cod_employee) REFERENCES public.employee(cod_employee);


--
-- TOC entry 3189 (class 2606 OID 34511)
-- Name: employee_user fkptbm19skj03rvssmuw8khql26; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_user
    ADD CONSTRAINT fkptbm19skj03rvssmuw8khql26 FOREIGN KEY (employee) REFERENCES public.employee(cod_employee);


-- Completed on 2022-04-04 18:00:50

--
-- PostgreSQL database dump complete
--

